[2020-06-13 12:10:27,585] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:10:27,594] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:10:27,594] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:10:27,594] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-13 12:10:27,594] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:10:27,614] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): greet> on 2020-06-01T10:00:00+00:00
[2020-06-13 12:10:27,616] {standard_task_runner.py:53} INFO - Started process 78774 to run task
[2020-06-13 12:10:27,673] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-13 12:10:27,684] {logging_mixin.py:112} INFO - Writing in file
[2020-06-13 12:10:27,685] {taskinstance.py:1145} ERROR - join() got an unexpected keyword argument 'path'
Traceback (most recent call last):
  File "/home/nineleaps/PycharmProjects/airflow_2/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/PycharmProjects/airflow_2/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/PycharmProjects/airflow_2/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/PycharmProjects/airflow_2/airflow/dags/simple_dag.py", line 13, in greet
    output_path = os.path.join(dirpath, path=PATH)
TypeError: join() got an unexpected keyword argument 'path'
[2020-06-13 12:10:27,686] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-13 12:10:37,568] {logging_mixin.py:112} INFO - [2020-06-13 12:10:37,567] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-06-13 12:17:22,190] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:17:22,203] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:17:22,203] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:17:22,203] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-13 12:17:22,203] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:17:22,217] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): greet> on 2020-06-01T10:00:00+00:00
[2020-06-13 12:17:22,219] {standard_task_runner.py:53} INFO - Started process 80249 to run task
[2020-06-13 12:17:22,282] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-13 12:17:22,295] {logging_mixin.py:112} INFO - Writing in file
[2020-06-13 12:17:22,295] {taskinstance.py:1145} ERROR - [Errno 2] No such file or directory: '/output/greet.txt'
Traceback (most recent call last):
  File "/home/nineleaps/PycharmProjects/airflow_2/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/PycharmProjects/airflow_2/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/PycharmProjects/airflow_2/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/PycharmProjects/airflow_2/airflow/dags/simple_dag.py", line 14, in greet
    with open(output_path, 'a+', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/output/greet.txt'
[2020-06-13 12:17:22,296] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-13 12:17:32,155] {logging_mixin.py:112} INFO - [2020-06-13 12:17:32,154] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-06-13 12:18:33,997] {taskinstance.py:663} INFO - Dependencies not met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'say_hi'}
[2020-06-13 12:18:33,997] {logging_mixin.py:112} INFO - [2020-06-13 12:18:33,997] {local_task_job.py:91} INFO - Task is not able to be run
[2020-06-13 12:23:56,336] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:23:56,345] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:23:56,346] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:23:56,346] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-13 12:23:56,346] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:23:56,361] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): greet> on 2020-06-01T10:00:00+00:00
[2020-06-13 12:23:56,363] {standard_task_runner.py:53} INFO - Started process 81783 to run task
[2020-06-13 12:23:56,409] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-13 12:23:56,421] {logging_mixin.py:112} INFO - Writing in file
[2020-06-13 12:23:56,422] {taskinstance.py:1145} ERROR - [Errno 2] No such file or directory: '/output/greet.txt'
Traceback (most recent call last):
  File "/home/nineleaps/PycharmProjects/airflow_2/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/PycharmProjects/airflow_2/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/PycharmProjects/airflow_2/venv/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/PycharmProjects/airflow_2/airflow/dags/simple_dag.py", line 14, in greet
    with open(output_path, 'a+', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/output/greet.txt'
[2020-06-13 12:23:56,422] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-13 12:24:06,313] {logging_mixin.py:112} INFO - [2020-06-13 12:24:06,312] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-06-13 12:37:20,895] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:37:20,905] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:37:20,905] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:37:20,905] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-13 12:37:20,905] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:37:20,920] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): greet> on 2020-06-01T10:00:00+00:00
[2020-06-13 12:37:20,922] {standard_task_runner.py:53} INFO - Started process 84643 to run task
[2020-06-13 12:37:20,998] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-13 12:37:21,016] {logging_mixin.py:112} INFO - Writing in file
[2020-06-13 12:37:21,017] {python_operator.py:114} INFO - Done. Returned value was: Greeted
[2020-06-13 12:37:21,033] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=simple_dag, task_id=greet, execution_date=20200601T100000, start_date=20200613T070720, end_date=20200613T070721
[2020-06-13 12:37:30,884] {logging_mixin.py:112} INFO - [2020-06-13 12:37:30,884] {local_task_job.py:103} INFO - Task exited with return code 0
[2020-06-13 12:44:11,493] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:44:11,508] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [queued]>
[2020-06-13 12:44:11,508] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:44:11,508] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-13 12:44:11,508] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-13 12:44:11,522] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): greet> on 2020-06-01T10:00:00+00:00
[2020-06-13 12:44:11,523] {standard_task_runner.py:53} INFO - Started process 86415 to run task
[2020-06-13 12:44:11,573] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: simple_dag.greet 2020-06-01T10:00:00+00:00 [running]> nineleaps-ThinkPad-E480
[2020-06-13 12:44:11,584] {logging_mixin.py:112} INFO - Writing in file
[2020-06-13 12:44:11,584] {logging_mixin.py:112} INFO - /home/nineleaps/PycharmProjects/airflow_2/output/greet.txt
[2020-06-13 12:44:11,584] {python_operator.py:114} INFO - Done. Returned value was: Greeted
[2020-06-13 12:44:11,600] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=simple_dag, task_id=greet, execution_date=20200601T100000, start_date=20200613T071411, end_date=20200613T071411
[2020-06-13 12:44:21,475] {logging_mixin.py:112} INFO - [2020-06-13 12:44:21,475] {local_task_job.py:103} INFO - Task exited with return code 0
